# Cloudflare Pages configuration
# This file is used for Pages deployment settings
# Configure build settings in the Cloudflare Pages dashboard instead

name = "goldenf-blog"
compatibility_date = "2024-07-15"

# Pages build output directory
pages_build_output_dir = "out"

# Environment variables for Pages
# Set these in the Cloudflare Pages dashboard:
# - NEXT_PUBLIC_SUPABASE_URL
# - NEXT_PUBLIC_SUPABASE_ANON_KEY  
# - SUPABASE_SERVICE_ROLE_KEY
# - NEXTAUTH_SECRET
# - NEXTAUTH_URL
# - DATABASE_URL